version: '3.7'

services:

  build-abstractions:
    build:
      context: .
      target: pack
      # build | test | pack | publish
    environment:
      NUGET_PROJECT: Aska.Core.EntityStorage.Abstractions
      #NUGET_KEY: todo - from CI env
      #NUGET_VERSION: todo - from CI env
    restart: on-failure
    
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: askaone
      MYSQL_DATABASE: askaone
      MYSQL_USER: askaone
      MYSQL_PASSWORD: askaone
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      
  postgresql:
    image: postgres:latest     
    restart: always
    environment:
      POSTGRES_PASSWORD: askaone
      POSTGRES_USER: askaone 
      POSTGRES_DB: askaone
      PGDATA: /data/postgres      
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    

volumes:
  mysql:
  postgres:

 #todo: compose files for test and publish 