// <auto-generated />
using System;
using Aska.Core.EntityStorage.DemoApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aska.Core.EntityStorage.DemoApp.Migrations.DemoSqlite
{
    [DbContext(typeof(DemoSqliteContext))]
    [Migration("20191117152332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Aska.Core.EntityStorage.DemoApp.SqliteEntity", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.ToTable("SqliteEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
