// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Aska.Core.EntityStorage.DemoApp.Migrations.DemoSqlite
{
    [DbContext(typeof(DemoSqliteContext))]
    partial class DemoSqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Aska.Core.EntityStorage.DemoApp.SqliteEntity", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.ToTable("SqliteEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
