// <auto-generated />
using System;
using Aska.Core.EntityStorage.DemoApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aska.Core.EntityStorage.DemoApp.Migrations.DemoPsql
{
    [DbContext(typeof(DemoPsqlContext))]
    partial class DemoPsqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Aska.Core.EntityStorage.DemoApp.PsqlEntity", b =>
                {
                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.ToTable("PsqlEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
