// <auto-generated />
using System;
using Aska.Core.EntityStorage.Ef.MariaDb.Tests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aska.Core.EntityStorage.Ef.MariaDb.Tests.Migrations
{
    [DbContext(typeof(TestMariaDbContext))]
    partial class TestMariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aska.Core.EntityStorage.Ef.MariaDb.Tests.TestDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("TestDbEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
